name = "mem1-cf"
main = "src/index.js"
compatibility_date = "2025-01-01"
account_id = "b04d087496afbef848ef0732834daaf8"
workers_dev = true

# ── KV Namespace ──────────────────────────────────────────────────────────
kv_namespaces = [
  { binding = "KV_NAMESPACE", id = "9af60c4b7fb34d22ac29dfd71e29ebd6" }
]

# ── Environment Variables ─────────────────────────────────────────────────
[vars]
API_KEY = "Pa$$w0rd"
